# 公共配置

server:
  port: 8080

spring:
  # 激活的环境配置文件 (根据不同电脑修改此处)
  profiles:
    active: dev_work  # 可选: dev_home, dev_work, prod

  # 数据源配置 - 移动到各环境配置文件中
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间，默认30秒，单位是毫秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: BDSPHikariPool # 连接池名称

  jackson:
    time-zone: GMT+8

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


springdoc:
  default-flat-param-object: true